export interface NSETicker {
  ticker: string;
  companyName: string;
}

export const NSE_TICKERS: NSETicker[] = [
  { ticker: 'RELIANCE', companyName: 'Reliance Industries Ltd' },
  { ticker: 'TCS', companyName: 'Tata Consultancy Services Ltd' },
  { ticker: 'HDFCBANK', companyName: 'HDFC Bank Ltd' },
  { ticker: 'INFY', companyName: 'Infosys Ltd' },
  { ticker: 'ICICIBANK', companyName: 'ICICI Bank Ltd' },
  { ticker: 'HINDUNILVR', companyName: 'Hindustan Unilever Ltd' },
  { ticker: 'SBIN', companyName: 'State Bank of India' },
  { ticker: 'BHARTIARTL', companyName: 'Bharti Airtel Ltd' },
  { ticker: 'ITC', companyName: 'ITC Ltd' },
  { ticker: 'KOTAKBANK', companyName: 'Kotak Mahindra Bank Ltd' },
  { ticker: 'LT', companyName: 'Larsen & Toubro Ltd' },
  { ticker: 'AXISBANK', companyName: 'Axis Bank Ltd' },
  { ticker: 'BAJFINANCE', companyName: 'Bajaj Finance Ltd' },
  { ticker: 'ASIANPAINT', companyName: 'Asian Paints Ltd' },
  { ticker: 'MARUTI', companyName: 'Maruti Suzuki India Ltd' },
  { ticker: 'SUNPHARMA', companyName: 'Sun Pharmaceutical Industries Ltd' },
  { ticker: 'TITAN', companyName: 'Titan Company Ltd' },
  { ticker: 'WIPRO', companyName: 'Wipro Ltd' },
  { ticker: 'ULTRACEMCO', companyName: 'UltraTech Cement Ltd' },
  { ticker: 'NESTLEIND', companyName: 'Nestle India Ltd' },
  { ticker: 'TATAMOTORS', companyName: 'Tata Motors Ltd' },
  { ticker: 'TATASTEEL', companyName: 'Tata Steel Ltd' },
  { ticker: 'POWERGRID', companyName: 'Power Grid Corporation of India Ltd' },
  { ticker: 'NTPC', companyName: 'NTPC Ltd' },
  { ticker: 'M&M', companyName: 'Mahindra & Mahindra Ltd' },
  { ticker: 'HCLTECH', companyName: 'HCL Technologies Ltd' },
  { ticker: 'ONGC', companyName: 'Oil & Natural Gas Corporation Ltd' },
  { ticker: 'TECHM', companyName: 'Tech Mahindra Ltd' },
  { ticker: 'ADANIENT', companyName: 'Adani Enterprises Ltd' },
  { ticker: 'ADANIPORTS', companyName: 'Adani Ports and SEZ Ltd' },
  { ticker: 'COALINDIA', companyName: 'Coal India Ltd' },
  { ticker: 'BAJAJFINSV', companyName: 'Bajaj Finserv Ltd' },
  { ticker: 'JSWSTEEL', companyName: 'JSW Steel Ltd' },
  { ticker: 'BPCL', companyName: 'Bharat Petroleum Corporation Ltd' },
  { ticker: 'GRASIM', companyName: 'Grasim Industries Ltd' },
  { ticker: 'DIVISLAB', companyName: 'Divi\'s Laboratories Ltd' },
  { ticker: 'DRREDDY', companyName: 'Dr. Reddy\'s Laboratories Ltd' },
  { ticker: 'CIPLA', companyName: 'Cipla Ltd' },
  { ticker: 'EICHERMOT', companyName: 'Eicher Motors Ltd' },
  { ticker: 'HEROMOTOCO', companyName: 'Hero MotoCorp Ltd' },
  { ticker: 'APOLLOHOSP', companyName: 'Apollo Hospitals Enterprise Ltd' },
  { ticker: 'SBILIFE', companyName: 'SBI Life Insurance Company Ltd' },
  { ticker: 'BRITANNIA', companyName: 'Britannia Industries Ltd' },
  { ticker: 'INDUSINDBK', companyName: 'IndusInd Bank Ltd' },
  { ticker: 'HDFCLIFE', companyName: 'HDFC Life Insurance Company Ltd' },
  { ticker: 'TATACONSUM', companyName: 'Tata Consumer Products Ltd' },
  { ticker: 'HINDALCO', companyName: 'Hindalco Industries Ltd' },
  { ticker: 'BAJAJ-AUTO', companyName: 'Bajaj Auto Ltd' },
  { ticker: 'VEDL', companyName: 'Vedanta Ltd' },
  { ticker: 'ZOMATO', companyName: 'Zomato Ltd' },
];

export const SITE_CONFIG = {
  name: 'TRON NSE',
  description: 'AI-Powered Financial Intelligence for NSE India Stocks',
  url: 'https://tron-nse.vercel.app',
  ogImage: '/og-image.png',
  keywords: [
    'NSE',
    'Indian stocks',
    'stock analysis',
    'AI stock scoring',
    'financial intelligence',
    'NIFTY 50',
    'BSE',
    'stock market India',
  ],
  author: 'TRON NSE',
  exchange: 'NSE',
  currency: 'INR',
  country: 'India',
  defaultTicker: 'RELIANCE',
  maxSearchResults: 10,
  maxRecentSearches: 20,
  maxPopularTickers: 10,
} as const;
